steps:
- name: python
  entrypoint: pip
  args: ["install", "-r", "pipeline/requirements.txt", "--user"]

  # Compile pipeline
- name: 'python'
  entrypoint: 'python'
  args: ['pipeline/pipeline.py']
  id: 'compile'

  # Upload compiled pipeline to GCS.
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'pipeline.json', 'gs://df-data-science-test-pipelines/$BRANCH_NAME/pipeline.json']
  id:  'upload'
  waitFor: ['compile']


