steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west4-docker.pkg.dev/df-data-science-test/df-ds-repo/scheduler', '.' ]
images: ['europe-west4-docker.pkg.dev/df-data-science-test/df-ds-repo/scheduler']

