timeout: 1200s
steps:
- id: 'tf init'
  name: us-central1-docker.pkg.dev/ny-dol-cloudbuild/ny-dol-tf-runners/terraform
  dir: 'environments/workload'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      
        for dir in $(ls -d */);
        do 
            if [ "${dir}" == "dev/" ];then
              cd ${dir}
              env=${dir%*/}
              env=${env#*/}
              echo ""
              echo "*************** TERRAFORM INIT ******************"
              echo "******* At environment: workload/${env} *********"
              echo "*************************************************"
              terraform init || exit 1
              cd -
            fi
         cd ../ 
        done
  
- id: 'tf validate'
  name: us-central1-docker.pkg.dev/ny-dol-cloudbuild/ny-dol-tf-runners/terraform
  dir: 'environments/workload'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      
        for dir in $(ls -d */);
        do 
            if [ "${dir}" == "dev/" ];then
              cd ${dir}
              env=${dir%*/}
              env=${env#*/}
              echo ""
              echo "*************** TERRAFORM VALIDATE ******************"
              echo "******* At environment: workload/${env} *********"
              echo "*************************************************"
              terraform validate || exit 1
              cd -
            fi
         cd ../ 
        done

- id: 'tf plan'
  name: us-central1-docker.pkg.dev/ny-dol-cloudbuild/ny-dol-tf-runners/terraform
  dir: 'environments/workload'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      
        for dir in $(ls -d */);
        do 
            if [ "${dir}" == "dev/" ];then
              cd ${dir}
              env=${dir%*/}
              env=${env#*/}
              echo ""
              echo "*************** TERRAFORM PLAN ******************"
              echo "******* At environment: workload/${env} *********"
              echo "*************************************************"
              terraform plan || exit 1
              cd -
            fi
         cd ../ 
        done

#- id: 'tf plan'
#  name: hashicorp/terraform:0.15.3
#  dir: '.'
#  entrypoint: 'sh'
#  args: 
#  - '-c'
#  - |
      
#        for dir in $(ls -d */);
#        do 
#          cd ${dir}   
#          env=${dir%*/}
#          env=${env#*/}
#          echo ""
#          echo "*************** TERRAFORM INIT ******************"
#          echo "******* At environment: ${env} ********"
#          echo "*************************************************"
#          terraform plan \
#              -input=false \
#              -out="./${BUILD_ID}_${PROJECT_NUMBER}.plan" || exit 1
#          cd -
#        done
#artifacts:
#  objects:
#    location: 'gs://cloudbuild_artifacts_gcs/terraform/cloudbuild/plan/$BUILD_ID'
#    paths: ['cloudbuild_pull_request.yaml', 'tfplan']   
