{{- if .Values.doppler.applicationSecret }}
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: {{ .Values.version}}-{{ .Values.app }}-{{ .Values.environment }} # DopplerSecret Name
  namespace: doppler-operator-system
  labels:
    {{- include "helm.labels" . | nindent 4 }}  
spec:
  tokenSecret: # Kubernetes service token secret (namespace defaults to doppler-operator-system)
    name: {{ .Values.version}}-{{ .Values.app }}-doppler-token
    namespace: doppler-operator-system
  managedSecret: # Kubernetes managed secret (will be created if does not exist)
    name: {{ .Values.version}}-{{ .Values.app }}
    namespace: {{ .Release.Namespace }} # Should match the namespace of deployments that will use the secret  
{{- end }}