{{- if .Values.doppler.applicationSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.version}}-{{ .Values.app }}-doppler-token
  namespace: doppler-operator-system
  labels:
    {{- include "helm-template.labels" . | nindent 4 }}
type: Opaque
data:
  serviceToken: {{ .Values.doppler.serviceToken | b64enc  }}
{{- end }}  


