apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.version}}-{{ .Values.app }}
  labels:
    {{- include "helm-template.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 2 }}
  {{- end }}  
  selector:
    {{- include "helm-template.selectorLabels" . | nindent 4 }}
