# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:0.15.3'
  dir: 'environments/workstream'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      #if [ -d "environments/$BRANCH_NAME/" ]; then
        for dir in $(ls -d */);
        do 
          cd ${dir}   
          env=${dir%*/}
          env=${env#*/}
          echo ""
          echo "*************** TERRAFORM INIT ******************"
          echo "******* At environment: ${env} ********"
          echo "*************************************************"
          terraform plan || exit 1
          cd -
        done
      #else
      #  echo "***************************** SKIPPING APPLYING *******************************"
      #  echo "Branch '$BRANCH_NAME' does not represent an oficial environment."
      #  echo "*******************************************************************************"
      #fi
# [END tf-apply]  