# [START tf-apply]
steps:
- id: 'tf init'
  name: hashicorp/terraform:0.15.3
  dir: 'environments/workstream'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      
        for dir in $(ls -d */);
        do 
          cd ${dir}   
          env=${dir%*/}
          env=${env#*/}
          echo ""
          echo "*************** TERRAFORM INIT ******************"
          echo "******* At environment: ${env} ********"
          echo "*************************************************"
          terraform init || exit 1
          cd -
        done
        
# [END tf-apply]  